diagnosis/urls.py
from django.conf.urls import url

from . import views

app_name = 'diagnosis'
urlpatterns = [
    # ex: /diagnosis/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /diagnosis/5/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # ex: /diagnosis/5/results/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /diagnosis/5/vote/
    url(r'^(?P<questiondiagnosis_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from shindan.views import kakikomi

urlpatterns = [
    url(r'^diagnosis/',include('diagnosis.urls')),
    url(r'^polls/',include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'', include('polls.urls')),
    url('^kakikomi1/$', kakikomi),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # ex: /polls/5/results/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

diagnosis/models.py
import datetime
from django.db import models
from django.utils import timezone
from django import forms


class QuestionDiagnosis(models.Model):
    questiondiagnosis_title = models.CharField(max_length=200)
    questiondiagnosis_text = models.TextField()
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.questiondiagnosis_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Hint(models.Model):
    questiondiagnosis = models.ForeignKey(QuestionDiagnosis, on_delete=models.CASCADE)
    hint_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.hint_text

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_title = models.CharField(max_length=200)
    question_text = models.TextField()
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

shindan/models.py
import datetime
from django.db import models
from django.utils import timezone

class QuestionShindan(models.Model):
    questionShindan_title = models.CharField(max_length=200)
    questionShindan_text = models.TextField()
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.questionShindan_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Answer(models.Model):
    question = models.ForeignKey(QuestionShindan, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.answer_text

shindan/forms.py
from django import forms

class KakikomiForm(forms.Form):
     name = forms.CharField()
     email = forms.EmailField()
     namefriend = forms.CharField()
     body = forms.CharField()

diagnosis/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from .models import Hint, QuestionDiagnosis
from django.urls import reverse
from django.views import generic
from django.utils import timezone
import random



class IndexView(generic.ListView):
    template_name = 'diagnosis/index.html'
    context_object_name = 'latest_questiondiagnosis_list'
#    def get_queryset(self):
#        """Return the last five published questions."""
#        return QuestionDiagnosis.objects.order_by('-pub_date')[:5]
    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return QuestionDiagnosis.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:55]


class DetailView(generic.DetailView):
    model = QuestionDiagnosis
    template_name = 'diagnosis/detail.html'
    def get_queryset(self):
        """
        Excludes any questiondiagnosis that aren't published yet.
        """
        return QuestionDiagnosis.objects.filter(pub_date__lte=timezone.now())




class ResultsView(generic.DetailView):
    model = QuestionDiagnosis
    template_name = 'diagnosis/results.html'



def vote(request, questiondiagnosis_id):
    questiondiagnosis = get_object_or_404(QuestionDiagnosis, pk=questiondiagnosis_id)
    try:
        selected_hint = questiondiagnosis.hint_set.get(pk=request.POST['hint'])
    except (KeyError, Hint.DoesNotExist):
        # Redisplay the question voting form.
        return HttpResponseRedirect(reverse('diagnosis:results', args=(questiondiagnosis.id,)))
    else:
        selected_hint.votes += 1
        selected_hint.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('diagnosis:results', args=(questiondiagnosis.id,)))

polls/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from .models import Choice, Question
from django.urls import reverse
from django.views import generic
from django.utils import timezone



class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
#    def get_queryset(self):
#        """Return the last five published questions."""
#        return Question.objects.order_by('-pub_date')[:5]
    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:55]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

#def vote(request, question_id):
#    return HttpResponse("You're voting on question %s." % question_id)
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "エラー：何も選択されていません。",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

shindan/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response
# Create your views here.
from django.http import HttpResponse
from .forms import KakikomiForm
from django.urls import reverse

def kakikomi(request):
     f = KakikomiForm()
     return HttpResponse(f.as_table())

diagnosis/templates/diagnosis/detail.html
{% extends 'diagnosis/index.html' %}
{% load staticfiles %}

{% block content %}
<ul>
<h1><a>{{ questiondiagnosis.questiondiagnosis_title }}</a></h1>
    <img src="/static/diagnosis/images/thumb{{questiondiagnosis.id}}.jpg"><br>
            <h2>
            <p>{{ questiondiagnosis.questiondiagnosis_text|linebreaks }}</p>
              {% if error_message %}
              <p>
                <strong>
                  {{ error_message }}
                </strong>
              </p>
              {% endif %}
            </h2>

              <input type="text" name="name" id="id_name" /><br><br>
              <form action="{% url 'diagnosis:vote' questiondiagnosis.id %}" method="post">
                {% csrf_token %}
              <input type="submit" value="診断する" class="sbt_1" />
            </form>
</ul>
{% endblock %}

diagnosis/templates/diagnosis/index.html
{% load staticfiles %}
<html>
<head>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-104070078-1', 'auto');
    ga('send', 'pageview');

  </script>
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script>
    (adsbygoogle = window.adsbygoogle || []).push({
      google_ad_client: "ca-pub-2658936999314130",
      enable_page_level_ads: true
    });
  </script>
  <title>Meloon</title>
  <script type="text/javascript">
  if ((navigator.userAgent.indexOf('iPhone') > 0 && navigator.userAgent.indexOf('iPad') == -1) || navigator.userAgent.indexOf('iPod') > 0 || navigator.userAgent.indexOf('Android') > 0) {
    document.write('<link rel="stylesheet" href="{% static 'css/sp_diagnosis.css' %}">');
  }else {
        document.write('<link rel="stylesheet" href="{% static 'css/diagnosis.css' %}">');
    }
</script>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <link href="https://fonts.googleapis.com/earlyaccess/roundedmplus1c.css" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css?family=Lobster+Two:400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Audiowide|Bungee+Outline|Lobster" rel="stylesheet">
  <script type="text/javascript">
  if ((navigator.userAgent.indexOf('iPhone') > 0 && navigator.userAgent.indexOf('iPad') == -1) || navigator.userAgent.indexOf('iPod') > 0 || navigator.userAgent.indexOf('Android') > 0) {
    document.write('<link rel="stylesheet" href="{% static 'css/sp_diagnosis.css' %}">');
  }else {
        document.write('<link rel="stylesheet" href="{% static 'css/diagnosis.css' %}">');
    }
</script>
</head>




<div class="page-header">
    <h1><a href="/diagnosis">Meloon<br><h4> みんなで決める、なんでも総選挙</h4></a></h1>
</div>
<!--<link rel="stylesheet" type="text/css" href="{% static 'diagnosis/style.css' %}" />-->
    <body>
      <div class="content container">
          <div class="row">
              <div class="col-md-8">
                <div class="post">
                  {% block content %}
                  {% if latest_questiondiagnosis_list %}
                  <ul>
                    {% for questiondiagnosis in latest_questiondiagnosis_list %}
                    <h1><a href="{% url 'diagnosis:detail' questiondiagnosis.id %}">{{ questiondiagnosis.questiondiagnosis_title }}</a></h1>
                    <a href="{% url 'diagnosis:detail' questiondiagnosis.id %}"><img src="/static/diagnosis/images/thumb{{questiondiagnosis.id}}.jpg"></a>
                    {% endfor %}
                  </ul>
                  {% else %}
                  <p>No diagnosis are available.</p>
                  {% endif %}
                  {% endblock %}
              </div>
            </div>
        </div>
  </div>

  </body>
</html>

diagnosis/templates/diagnosis/results.html
hint{% extends 'diagnosis/index.html' %}
{% load staticfiles %}

{% block content %}
<ul>
        <h1><a>{{ questiondiagnosis.questiondiagnosis_title }}</a></h1>
        <img src="{% static 'diagnosis/images/thumb1.jpg' %}"><br>
        <br>
        <h2>
        <p>{{ questiondiagnosis.questiondiagnosis_text|linebreaks }}</p></h2>

        <ul>
          <h1>
          {% for hint in questiondiagnosis.hint_set.all %}
          <li><strong>{{ hint.hint_text }}</strong></li><br>
          {% endfor %}
        </h1>
        </ul>

        <input type="submit" value="もう1度" onclick="location.href='{% url 'diagnosis:detail' questiondiagnosis.id %}'" class="sbt_1" />
</ul>
{% endblock %}

mysite/templates/shindan/kakikomiform.html
{% load staticfiles %}
<html>
<head>
     <title>書き込みフォーム</title>
</head>
<body>
<h1>掲示板 - 書き込みフォーム</h1>
<form action="" method="post">
     <table>
          {{form1.as_table}}
     </table>
</form>
</body>
</html>

polls/templates/polls/detail.html
{% extends 'polls/index.html' %}
{% load staticfiles %}

{% block content %}
<ul>
<h1><a>{{ question.question_title }}</a></h1>
    <img src="/static/polls/images/thumb{{question.id}}.jpg"><br>
            <br>
            <h2>
            <p>{{ question.question_text|linebreaks }}</p>
              {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}</h2>

            <h1><form action="{% url 'polls:vote' question.id %}" method="post">
              {% csrf_token %}
              {% for choice in question.choice_set.all %}
              <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
              <label for="choice{{ forloop.counter }}" class="radio">{{ choice.choice_text }}</label><br><br>
              {% endfor %}</h1>
              <input type="submit" value="投票する" class="sbt_1" />
            </form>
</ul>
{% endblock %}

polls/templates/polls/index.html
{% load staticfiles %}
<html>
<head>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-104070078-1', 'auto');
    ga('send', 'pageview');

  </script>
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script>
    (adsbygoogle = window.adsbygoogle || []).push({
      google_ad_client: "ca-pub-2658936999314130",
      enable_page_level_ads: true
    });
  </script>
  <title>Meloon</title>
  <script type="text/javascript">
  if ((navigator.userAgent.indexOf('iPhone') > 0 && navigator.userAgent.indexOf('iPad') == -1) || navigator.userAgent.indexOf('iPod') > 0 || navigator.userAgent.indexOf('Android') > 0) {
    document.write('<link rel="stylesheet" href="{% static 'css/sp_polls.css' %}">');
  }else {
        document.write('<link rel="stylesheet" href="{% static 'css/polls.css' %}">');
    }
</script>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <link href="https://fonts.googleapis.com/earlyaccess/roundedmplus1c.css" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css?family=Lobster+Two:400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Audiowide|Bungee+Outline|Lobster" rel="stylesheet">
  <script type="text/javascript">
  if ((navigator.userAgent.indexOf('iPhone') > 0 && navigator.userAgent.indexOf('iPad') == -1) || navigator.userAgent.indexOf('iPod') > 0 || navigator.userAgent.indexOf('Android') > 0) {
    document.write('<link rel="stylesheet" href="{% static 'css/sp_polls.css' %}">');
  }else {
        document.write('<link rel="stylesheet" href="{% static 'css/polls.css' %}">');
    }
</script>
</head>




<div class="page-header">
    <h1><a href="/polls">Meloon<br><h4> みんなで決める、なんでも総選挙</h4></a></h1>
</div>
<!--<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />-->
    <body>
      <div class="content container">
          <div class="row">
              <div class="col-md-8">
                <div class="post">
                  {% block content %}
                  {% if latest_question_list %}
                  <ul>
                    {% for question in latest_question_list %}
                    <h1><a href="{% url 'polls:detail' question.id %}">{{ question.question_title }}</a></h1>
                    <a href="{% url 'polls:detail' question.id %}"><img src="/static/polls/images/thumb{{question.id}}.jpg" ></a>
                    {% endfor %}
                  </ul>
                  {% else %}
                  <p>No polls are available.</p>
                  {% endif %}
                  {% endblock %}
              </div>
            </div>
        </div>
  </div>

  </body>
</html>

polls/templates/polls/results.html
{% extends 'polls/index.html' %}
{% load staticfiles %}

{% block content %}
<ul>
        <h1><a>{{ question.question_title }}</a></h1>
        <img src="/static/polls/images/thumb{{question.id}}.jpg"><br>
        <br>
        <h2>
        <p>{{ question.question_text|linebreaks }}</p></h2>

        <ul>
          <h1>
          {% for choice in question.choice_set.all %}
          <li><strong>{{ choice.choice_text }}</strong><br> 　得票数　 {{ choice.votes }} 票</li><br>
          {% endfor %}
        </h1>
        </ul>

        <input type="submit" value="もう1度" onclick="location.href='{% url 'polls:detail' question.id %}'" class="sbt_1" />
</ul>
{% endblock %}

shindan/templates/shindan/kakikomiform.html
{% load staticfiles %}
<html>
<head>
     <title>書き込みフォーム</title>
</head>
<body>
<h1>掲示板 - 書き込みフォーム</h1>
<form action="" method="post">
     <table>
          {{form1.as_table}}
     </table>
</form>
</body>
</html>